#!/bin/sh
case "$1" in
start) 	date >> /var/log/userdata.log 
	(/usr/bin/curl http://169.254.169.254/latest/user-data | /bin/bash - ) 2>\&1 >> /var/log/userdata.log
	;;
*) 	echo "Usage: $0 {start}"
	exit 1 ;;
esac

